### ISSUE TITLE
[EPIC] Сверстать главную страницу проекта X 

### ISSUE THREAD

**Issue by amidf** [amidf/mentor-projects#1]
**Общее:** Необходимо сверстать главную страницу лэндинга, посвященного X теме. Страница должна быть:
- Кроссбраузерной;
- Адаптивной;

Этапы будут следующие:
- [ ] Подготовить рабочее окружение;
- [ ] Определить основные повторяющиеся элементы и написать для них стили;
- [ ] Интегрировать БЭМ;

**Comment by amidf** [comment]
Добавлена шапка страницы. Десктопная и мобильная версии.

**Comment by amidf** [comment]
На **11.08.2019** надо добавить адаптивную версию баннера. Поэтому к дополнению основного списка этапов идёт задача:
- [ ] Добавить баннер;

Также если успеем, то сделать секцию с вкладками:
- [ ] Добавить секцию с вкладками;
